/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package positionlot;

import positionlot.main.MainClass;

public class App {

    public static void main(String[] args) {

        MainClass mainClass = new MainClass();
        mainClass.launch("");

    }
}
